-- Insert Test Emergency Requests
-- Fire Department Requests
INSERT INTO emergency_requests (victim_name, victim_phone, location, latitude, longitude, emergency_type, priority, status, description, assigned_team_id, created_by, created_at, updated_at) VALUES
('Sarah Johnson', '555-0101', '123 Main Street, Downtown', 40.7128, -74.0060, 'FIRE', 'CRITICAL', 'EN_ROUTE', 'Building fire with people trapped on 3rd floor. Heavy smoke visible.', 1, 'victim_test1', DATE_SUB(NOW(), INTERVAL 30 MINUTE), DATE_SUB(NOW(), INTERVAL 25 MINUTE)),
('Michael Chen', '555-0102', '456 Oak Avenue, Residential Area', 40.7589, -73.9851, 'FIRE', 'HIGH', 'ON_SCENE', 'House fire started in kitchen. Family evacuated safely.', 1, 'victim_test2', DATE_SUB(NOW(), INTERVAL 2 HOUR), DATE_SUB(NOW(), INTERVAL 1 HOUR)),
('Emily Rodriguez', '555-0103', '789 Pine Road, Suburbs', 40.7282, -73.7949, 'FIRE', 'MEDIUM', 'RESOLVED', 'Small electrical fire in garage. Contained before spreading.', 1, 'victim_test3', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 23 HOUR)),
-- Police Department Requests
('James Wilson', '555-0201', '321 Elm Street, Commercial District', 40.7484, -73.9857, 'CRIME', 'HIGH', 'ASSIGNED', 'Armed robbery in progress at convenience store. Suspects still on scene.', 3, 'victim_test4', DATE_SUB(NOW(), INTERVAL 15 MINUTE), DATE_SUB(NOW(), INTERVAL 10 MINUTE)),
('Lisa Anderson', '555-0202', '654 Maple Drive, Downtown', 40.7614, -73.9776, 'CRIME', 'CRITICAL', 'EN_ROUTE', 'Hostage situation at bank. Multiple civilians involved.', 3, 'victim_test5', DATE_SUB(NOW(), INTERVAL 45 MINUTE), DATE_SUB(NOW(), INTERVAL 40 MINUTE)),
('Robert Taylor', '555-0203', '987 Cedar Lane, Business Park', 40.7489, -73.9680, 'CRIME', 'MEDIUM', 'RESOLVED', 'Break-in at warehouse. Suspects apprehended.', 3, 'victim_test6', DATE_SUB(NOW(), INTERVAL 3 HOUR), DATE_SUB(NOW(), INTERVAL 2 HOUR)),
-- Medical Department Requests
('Jennifer Martinez', '555-0301', '147 Birch Avenue, Residential', 40.7300, -73.9950, 'MEDICAL', 'CRITICAL', 'ON_SCENE', 'Cardiac arrest. Patient unresponsive. CPR in progress.', 2, 'victim_test7', DATE_SUB(NOW(), INTERVAL 20 MINUTE), DATE_SUB(NOW(), INTERVAL 15 MINUTE)),
('David Lee', '555-0302', '258 Walnut Street, Park Area', 40.7410, -73.9897, 'MEDICAL', 'HIGH', 'ASSIGNED', 'Severe allergic reaction. Patient having difficulty breathing.', 2, 'victim_test8', DATE_SUB(NOW(), INTERVAL 35 MINUTE), DATE_SUB(NOW(), INTERVAL 30 MINUTE)),
('Amanda White', '555-0303', '369 Spruce Road, Shopping Mall', 40.7580, -73.9855, 'MEDICAL', 'MEDIUM', 'RESOLVED', 'Broken leg from fall. Patient stabilized and transported.', 2, 'victim_test9', DATE_SUB(NOW(), INTERVAL 5 HOUR), DATE_SUB(NOW(), INTERVAL 4 HOUR)),
-- Pending Requests (Unassigned - High Priority for Manual Assignment)
('Carlos Garcia', '555-0401', '741 Ash Boulevard, Industrial Zone', 40.7450, -73.9800, 'FIRE', 'CRITICAL', 'PENDING', 'Large chemical spill at industrial plant. Toxic fumes spreading. Requires hazmat team.', NULL, 'victim_test10', DATE_SUB(NOW(), INTERVAL 5 MINUTE), DATE_SUB(NOW(), INTERVAL 5 MINUTE)),
('Michelle Brown', '555-0402', '852 Hickory Lane, Residential', 40.7520, -73.9920, 'MEDICAL', 'HIGH', 'PENDING', 'Elderly patient fallen, possible hip fracture. Unable to move, in severe pain.', NULL, 'victim_test11', DATE_SUB(NOW(), INTERVAL 10 MINUTE), DATE_SUB(NOW(), INTERVAL 10 MINUTE)),
('Steven Kim', '555-0403', '963 Sycamore Drive, University Campus', 40.7350, -73.9960, 'CRIME', 'CRITICAL', 'PENDING', 'Active shooter reported on campus. Multiple witnesses calling. Students sheltering in place.', NULL, 'victim_test12', DATE_SUB(NOW(), INTERVAL 8 MINUTE), DATE_SUB(NOW(), INTERVAL 8 MINUTE)),
('Patricia Johnson', '555-0404', '1234 River Road, Waterfront', 40.7290, -74.0050, 'FIRE', 'HIGH', 'PENDING', 'Boat fire at marina. Multiple vessels at risk. High winds spreading flames.', NULL, 'victim_test13', DATE_SUB(NOW(), INTERVAL 3 MINUTE), DATE_SUB(NOW(), INTERVAL 3 MINUTE)),
('Thomas Davis', '555-0405', '567 Highland Avenue, Hills District', 40.7680, -73.9720, 'MEDICAL', 'CRITICAL', 'PENDING', 'Multi-vehicle accident on highway. At least 5 injured, 2 critical. Traffic blocked.', NULL, 'victim_test14', DATE_SUB(NOW(), INTERVAL 12 MINUTE), DATE_SUB(NOW(), INTERVAL 12 MINUTE)),
('Rebecca Miller', '555-0406', '890 Downtown Plaza, City Center', 40.7550, -73.9900, 'CRIME', 'HIGH', 'PENDING', 'Armed assault in progress. Victim stabbed, suspect fled on foot heading north.', NULL, 'victim_test15', DATE_SUB(NOW(), INTERVAL 7 MINUTE), DATE_SUB(NOW(), INTERVAL 7 MINUTE)),
('Daniel Wilson', '555-0407', '432 Forest Drive, Woodland Area', 40.7400, -73.9650, 'FIRE', 'MEDIUM', 'PENDING', 'Wildfire spreading near residential area. Multiple homes at risk. Smoke visible for miles.', NULL, 'victim_test16', DATE_SUB(NOW(), INTERVAL 15 MINUTE), DATE_SUB(NOW(), INTERVAL 15 MINUTE)),
('Karen Martinez', '555-0408', '789 Medical Center, Hospital District', 40.7620, -73.9880, 'MEDICAL', 'HIGH', 'PENDING', 'Mass food poisoning at restaurant. 15+ people ill, 3 critical. Need multiple ambulances.', NULL, 'victim_test17', DATE_SUB(NOW(), INTERVAL 6 MINUTE), DATE_SUB(NOW(), INTERVAL 6 MINUTE)),
('Christopher Lee', '555-0409', '345 Bank Street, Financial District', 40.7560, -73.9830, 'CRIME', 'CRITICAL', 'PENDING', 'Bank robbery with explosives threat. Building evacuated. Bomb squad needed urgently.', NULL, 'victim_test18', DATE_SUB(NOW(), INTERVAL 4 MINUTE), DATE_SUB(NOW(), INTERVAL 4 MINUTE)),
('Nancy Anderson', '555-0410', '678 School Road, Education Zone', 40.7470, -73.9910, 'FIRE', 'HIGH', 'PENDING', 'School building fire. All students evacuated but fire spreading to adjacent classrooms.', NULL, 'victim_test19', DATE_SUB(NOW(), INTERVAL 9 MINUTE), DATE_SUB(NOW(), INTERVAL 9 MINUTE)),
('Joseph Taylor', '555-0411', '901 Park Avenue, Recreation Area', 40.7380, -73.9750, 'MEDICAL', 'MEDIUM', 'PENDING', 'Child fell from playground equipment. Head injury, conscious but disoriented.', NULL, 'victim_test20', DATE_SUB(NOW(), INTERVAL 11 MINUTE), DATE_SUB(NOW(), INTERVAL 11 MINUTE)),
('Sandra White', '555-0412', '234 Transit Station, Transport Hub', 40.7510, -73.9780, 'CRIME', 'MEDIUM', 'PENDING', 'Pickpocketing ring operating at subway station. Multiple victims reported thefts.', NULL, 'victim_test21', DATE_SUB(NOW(), INTERVAL 13 MINUTE), DATE_SUB(NOW(), INTERVAL 13 MINUTE)),
('Brian Garcia', '555-0413', '567 Bridge Road, Infrastructure', 40.7430, -74.0020, 'FIRE', 'LOW', 'PENDING', 'Small car fire on bridge. Vehicle safely pulled over, no injuries. Traffic affected.', NULL, 'victim_test22', DATE_SUB(NOW(), INTERVAL 14 MINUTE), DATE_SUB(NOW(), INTERVAL 14 MINUTE)),
('Lisa Rodriguez', '555-0414', '890 Senior Center, Community Area', 40.7590, -73.9840, 'MEDICAL', 'HIGH', 'PENDING', 'Elderly resident having stroke symptoms. Left side weakness, slurred speech. Time critical.', NULL, 'victim_test23', DATE_SUB(NOW(), INTERVAL 2 MINUTE), DATE_SUB(NOW(), INTERVAL 2 MINUTE)),
('Mark Thompson', '555-0415', '123 Hotel Boulevard, Tourist District', 40.7540, -73.9790, 'CRIME', 'HIGH', 'PENDING', 'Hotel guest assault. Domestic violence situation. Victim needs immediate protection.', NULL, 'victim_test24', DATE_SUB(NOW(), INTERVAL 5 MINUTE), DATE_SUB(NOW(), INTERVAL 5 MINUTE)),
('Angela Moore', '555-0416', '456 Factory Lane, Manufacturing Zone', 40.7420, -73.9680, 'FIRE', 'CRITICAL', 'PENDING', 'Explosion at chemical factory. Multiple casualties. Hazardous materials released into air.', NULL, 'victim_test25', DATE_SUB(NOW(), INTERVAL 1 MINUTE), DATE_SUB(NOW(), INTERVAL 1 MINUTE)),
('Kevin Jackson', '555-0417', '789 Beach Road, Coastal Area', 40.7270, -74.0040, 'MEDICAL', 'CRITICAL', 'PENDING', 'Drowning incident. Swimmer pulled from water, not breathing. CPR started by bystanders.', NULL, 'victim_test26', DATE_SUB(NOW(), INTERVAL 3 MINUTE), DATE_SUB(NOW(), INTERVAL 3 MINUTE)),
('Melissa Harris', '555-0418', '321 Market Street, Shopping District', 40.7500, -73.9860, 'CRIME', 'MEDIUM', 'PENDING', 'Shoplifting incident escalated. Store security detained suspect, backup needed.', NULL, 'victim_test27', DATE_SUB(NOW(), INTERVAL 16 MINUTE), DATE_SUB(NOW(), INTERVAL 16 MINUTE)),
('Ryan Clark', '555-0419', '654 Construction Site, Development Area', 40.7460, -73.9730, 'MEDICAL', 'HIGH', 'PENDING', 'Worker fell from scaffolding. Multiple fractures, possible spinal injury. Needs extraction.', NULL, 'victim_test28', DATE_SUB(NOW(), INTERVAL 8 MINUTE), DATE_SUB(NOW(), INTERVAL 8 MINUTE)),
('Nicole Lewis', '555-0420', '987 Apartment Complex, Residential Tower', 40.7570, -73.9820, 'FIRE', 'MEDIUM', 'PENDING', 'Gas leak reported in apartment building. Residents evacuating. Strong odor on floors 8-12.', NULL, 'victim_test29', DATE_SUB(NOW(), INTERVAL 6 MINUTE), DATE_SUB(NOW(), INTERVAL 6 MINUTE)),
('Eric Walker', '555-0421', '147 Sports Arena, Entertainment District', 40.7530, -73.9770, 'MEDICAL', 'MEDIUM', 'PENDING', 'Spectator collapse during event. Possible heart attack. Crowd making access difficult.', NULL, 'victim_test30', DATE_SUB(NOW(), INTERVAL 10 MINUTE), DATE_SUB(NOW(), INTERVAL 10 MINUTE));

-- Update team statuses
UPDATE rescue_teams SET status = 'EN_ROUTE' WHERE id = 1;
UPDATE rescue_teams SET status = 'ON_SCENE' WHERE id = 2;
UPDATE rescue_teams SET status = 'EN_ROUTE' WHERE id = 3;

-- Update timestamps for assigned requests
UPDATE emergency_requests SET assigned_at = DATE_SUB(updated_at, INTERVAL 5 MINUTE) WHERE assigned_team_id IS NOT NULL AND status != 'PENDING';
UPDATE emergency_requests SET responded_at = DATE_SUB(updated_at, INTERVAL 2 MINUTE) WHERE status IN ('ON_SCENE', 'RESOLVED');
UPDATE emergency_requests SET completed_at = updated_at WHERE status = 'RESOLVED';
UPDATE emergency_requests SET resolution_notes = 'Situation resolved successfully. No casualties.' WHERE status = 'RESOLVED' AND resolution_notes IS NULL;
